services:
  api-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=src/__init__.py
      - FLASK_DEBUG=1
      - FLASK_ENV=Development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL_DEVELOPMENT=postgresql://postgres:postgres@api-db:5432/api_dev
      - DATABASE_URL_TEST=postgresql://postgres:postgres@api-db:5432/api_test
    depends_on:
      - api-db
    entrypoint: ['/usr/src/app/entrypoint.sh']